namespace SpriteKind {
    export const ТипВрага = SpriteKind.create()
    export const ТипФиниша = SpriteKind.create()
}

sprites.onOverlap(SpriteKind.Player, SpriteKind.ТипФиниша, function (sprite, otherSprite) {
    game.over(true)
})
let Игрок: Sprite = null
tiles.setCurrentTilemap(tilemap`level1`)
Игрок = sprites.create(sprites.castle.heroWalkFront1, SpriteKind.Player)
tiles.placeOnRandomTile(Игрок, sprites.dungeon.collectibleInsignia)
controller.moveSprite(Игрок, 80, 80)
scene.cameraFollowSprite(Игрок)
let Финиш = sprites.create(img`
    . . b b b b b b b b b b b b . .
    . b e 4 4 4 4 4 4 4 4 4 4 e b .
    b e 4 4 4 4 4 4 4 4 4 4 4 4 e b
    b e 4 4 4 4 4 4 4 4 4 4 4 4 e b
    b e 4 4 4 4 4 4 4 4 4 4 4 4 e b
    b e e 4 4 4 4 4 4 4 4 4 4 e e b
    b e e e e e e e e e e e e e e b
    b e e e e e e e e e e e e e e b
    b b b b b b b d d b b b b b b b
    c b b b b b b c c b b b b b b c
    c c c c c c b c c b c c c c c c
    b e e e e e c b b c e e e e e b
    b e e e e e e e e e e e e e e b
    b c e e e e e e e e e e e e c b
    b b b b b b b b b b b b b b b b
    . b b . . . . . . . . . . b b .
    `, SpriteKind.ТипФиниша)
tiles.placeOnRandomTile(Финиш, sprites.dungeon.chestClosed)
let Враг = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111ffff.....
    ......fffcdb1bc111cf....
    ....fc111cbfbf1b1b1f....
    ....f1b1b1ffffbfbfbf....
    ....fbfbfffffff.........
    .........fffff..........
    ..........fff...........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.ТипВрага)
tiles.placeOnRandomTile(Враг, sprites.dungeon.floorLight3)
